In [26]:
import numpy as np
A = np.mat([[2,4,4],
            [4,6,2],
            [2,2,3]])
u1 = np.mat([[3],[4],[2]])
u2 = np.mat([[-1],[2],[-2]])
u3 = np.mat([[4],[-2],[-1]])

u1 = u1 / (u1.T*u1).item()
u2 = u2 / (u2.T*u2).item()
u3 = u3 / (u3.T*u3).item()

P = np.concatenate([u1,u2,u3],axis=1)
print(P@np.mat([[10,0,0],
                [0,2,0],
                [0,0,-1]])@np.linalg.inv(P))
# print(P)
# print(10*H1+2*H2-H3)

[[2. 4. 4.]
 [4. 6. 2.]
 [2. 2. 3.]]


In [29]:
np.mat([[1,1],[1,-1]]) @ np.linalg.inv(np.mat([[1,2],[2,1]])) @ np.mat([[2,3],[3,4]])

matrix([[1.66666667, 2.33333333],
        [1.        , 1.        ]])